/**
 * AUTO-GENERATED FILE – DO NOT EDIT MANUALLY
 *
 * Minions here are PLAYER-SUMMONED ALLIES defined EXCLUSIVELY under the
 * @minions folder (nevermine2_source/minion/entity/).
 *
 * Generated by: scripts/fillMinions.js
 */

export const Minions = [
  {
    "entity": "EntityAlluricorn",
    "displayName": "Alluricorn",
    "health": 200,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 13,
    "damageMax": 13,
    "spawnTools": [
      {
        "itemId": "Itemizer.AlluricornSlab",
        "item": "AlluricornSlab",
        "usage": "Use AlluricornSlab to summon EntityAlluricorn.",
        "imageUrl": "/textures/items/alluricornSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/alluricorn/alluricorn.gltf"
  },
  {
    "entity": "EntityBlissard",
    "displayName": "Blissard",
    "health": 100,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 11,
    "damageMax": 11,
    "spawnTools": [
      {
        "itemId": "Itemizer.BlissardSlab",
        "item": "BlissardSlab",
        "usage": "Use BlissardSlab to summon EntityBlissard.",
        "imageUrl": "/textures/items/blissardSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/blissard/blissard.gltf"
  },
  {
    "entity": "EntityCompeer",
    "displayName": "Compeer",
    "health": 20,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 5,
    "damageMax": 5,
    "spawnTools": [
      {
        "itemId": "Itemizer.CompeerSlab",
        "item": "CompeerSlab",
        "usage": "Use CompeerSlab to summon EntityCompeer.",
        "imageUrl": "/textures/items/compeerSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/compeer/compeer.gltf"
  },
  {
    "entity": "EntityConstructServility",
    "displayName": "ConstructServility",
    "health": 260,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 15,
    "damageMax": 15,
    "spawnTools": [
      {
        "itemId": "Itemizer.ConstructServilitySlab",
        "item": "ConstructServilitySlab",
        "usage": "Use ConstructServilitySlab to summon EntityConstructServility.",
        "imageUrl": "/textures/items/constructServilitySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/construct-servility/construct-servility.gltf"
  },
  {
    "entity": "EntityCorby",
    "displayName": "Corby",
    "health": 200,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 11,
    "damageMax": 11,
    "spawnTools": [
      {
        "itemId": "Itemizer.CorbySlab",
        "item": "CorbySlab",
        "usage": "Use CorbySlab to summon EntityCorby.",
        "imageUrl": "/textures/items/corbySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/corby/corby.gltf"
  },
  {
    "entity": "EntityCraggy",
    "displayName": "Craggy",
    "health": 180,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.CraggySlab",
        "item": "CraggySlab",
        "usage": "Use CraggySlab to summon EntityCraggy.",
        "imageUrl": "/textures/items/craggySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/craggy/craggy.gltf"
  },
  {
    "entity": "EntityDraggy",
    "displayName": "Draggy",
    "health": 100,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.DraggySlab",
        "item": "DraggySlab",
        "usage": "Use DraggySlab to summon EntityDraggy.",
        "imageUrl": "/textures/items/draggySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/draggy/draggy.gltf"
  },
  {
    "entity": "EntityEnderCarrier",
    "displayName": "EnderCarrier",
    "health": 100,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 7,
    "damageMax": 7,
    "spawnTools": [
      {
        "itemId": "Itemizer.EnderCarrierSlab",
        "item": "EnderCarrierSlab",
        "usage": "Use EnderCarrierSlab to summon EntityEnderCarrier.",
        "imageUrl": "/textures/items/enderCarrierSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/ender-carrier/ender-carrier.gltf"
  },
  {
    "entity": "EntityGnawer",
    "displayName": "Gnawer",
    "health": 430,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 9,
    "damageMax": 9,
    "spawnTools": [
      {
        "itemId": "Itemizer.GnawerSlab",
        "item": "GnawerSlab",
        "usage": "Use GnawerSlab to summon EntityGnawer.",
        "imageUrl": "/textures/items/gnawerSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/gnawer/gnawer.gltf"
  },
  {
    "entity": "EntityGoofer",
    "displayName": "Goofer",
    "health": 270,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 0,
    "damageMax": 0,
    "spawnTools": [
      {
        "itemId": "Itemizer.GooferSlab",
        "item": "GooferSlab",
        "usage": "Use GooferSlab to summon EntityGoofer.",
        "imageUrl": "/textures/items/gooferSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/goofer/goofer.gltf"
  },
  {
    "entity": "EntityHealingGolem",
    "displayName": "HealingGolem",
    "health": 200,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 6,
    "damageMax": 6,
    "spawnTools": [
      {
        "itemId": "Itemizer.HealingGolemSlab",
        "item": "HealingGolemSlab",
        "usage": "Use HealingGolemSlab to summon EntityHealingGolem.",
        "imageUrl": "/textures/items/healingGolemSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/healing-golem/healing-golem.gltf"
  },
  {
    "entity": "EntityHellquin",
    "displayName": "Hellquin",
    "health": 120,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.HellquinSlab",
        "item": "HellquinSlab",
        "usage": "Use HellquinSlab to summon EntityHellquin.",
        "imageUrl": "/textures/items/hellquinSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/hellquin/hellquin.gltf"
  },
  {
    "entity": "EntityHiveSoldier",
    "displayName": "HiveSoldier",
    "health": 25,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Weaponizer.HiveStaff",
        "item": "HiveStaff",
        "usage": "Use HiveStaff to summon EntityHiveSoldier.",
        "imageUrl": "/textures/items/hiveStaff.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/hive-soldier/hive-soldier.gltf"
  },
  {
    "entity": "EntityHorntail",
    "displayName": "Horntail",
    "health": 270,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 18,
    "damageMax": 18,
    "spawnTools": [
      {
        "itemId": "Itemizer.HorntailSlab",
        "item": "HorntailSlab",
        "usage": "Use HorntailSlab to summon EntityHorntail.",
        "imageUrl": "/textures/items/horntailSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/horntail/horntail.gltf"
  },
  {
    "entity": "EntityMechaCyclops",
    "displayName": "MechaCyclops",
    "health": 100,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 30,
    "damageMax": 30,
    "spawnTools": [
      {
        "itemId": "Itemizer.MechaCyclopsSlab",
        "item": "MechaCyclopsSlab",
        "usage": "Use MechaCyclopsSlab to summon EntityMechaCyclops.",
        "imageUrl": "/textures/items/mechaCyclopsSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/mecha-cyclops/mecha-cyclops.gltf"
  },
  {
    "entity": "EntityMechaSkellox",
    "displayName": "MechaSkellox",
    "health": 160,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 15,
    "damageMax": 15,
    "spawnTools": [
      {
        "itemId": "Itemizer.MechaSkelloxSlab",
        "item": "MechaSkelloxSlab",
        "usage": "Use MechaSkelloxSlab to summon EntityMechaSkellox.",
        "imageUrl": "/textures/items/mechaSkelloxSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/mecha-skellox/mecha-skellox.gltf"
  },
  {
    "entity": "EntityOrbling",
    "displayName": "Orbling",
    "health": 10,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 0,
    "damageMax": 0,
    "spawnTools": [
      {
        "itemId": "Armorizer.SpaceKingBoots",
        "item": "SpaceKingBoots",
        "usage": "Wearing the full Space King armor set sometimes summons an Orbling when you are hurt.",
        "imageUrl": "/dimensions/common_images/Spaceking_Boots.png",
        "source": "armor-effect/manual"
      }
    ],
    "model": "/models/_auto-minions/common/orbling/orbling.gltf"
  },
  {
    "entity": "EntityPenguin",
    "displayName": "Penguin",
    "health": 100,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.PenguinSlab",
        "item": "PenguinSlab",
        "usage": "Use PenguinSlab to summon EntityPenguin.",
        "imageUrl": "/textures/items/penguinSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/penguin/penguin.gltf"
  },
  {
    "entity": "EntityPlateosaur",
    "displayName": "Plateosaur",
    "health": 320,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 5,
    "damageMax": 5,
    "spawnTools": [
      {
        "itemId": "Itemizer.PlateosaurSlab",
        "item": "PlateosaurSlab",
        "usage": "Use PlateosaurSlab to summon EntityPlateosaur.",
        "imageUrl": "/textures/items/plateosaurSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/plateosaur/plateosaur.gltf"
  },
  {
    "entity": "EntityRammerhorn",
    "displayName": "Rammerhorn",
    "health": 210,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 11,
    "damageMax": 11,
    "spawnTools": [
      {
        "itemId": "Itemizer.RammerhornSlab",
        "item": "RammerhornSlab",
        "usage": "Use RammerhornSlab to summon EntityRammerhorn.",
        "imageUrl": "/textures/items/rammerhornSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/rammerhorn/rammerhorn.gltf"
  },
  {
    "entity": "EntityRosid",
    "displayName": "Rosid",
    "health": 20,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 6,
    "damageMax": 6,
    "spawnTools": [
      {
        "itemId": "Armorizer.RosidianBoots",
        "item": "RosidianBoots",
        "usage": "Wearing the full Rosidian armor set periodically summons a Rosid companion.",
        "imageUrl": "/dimensions/common_images/Rosidian_Boots.png",
        "source": "armor-effect/manual"
      }
    ],
    "model": "/models/_auto-minions/common/rosid/rosid.gltf"
  },
  {
    "entity": "EntityShaddy",
    "displayName": "Shaddy",
    "health": 200,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.ShaddySlab",
        "item": "ShaddySlab",
        "usage": "Use ShaddySlab to summon EntityShaddy.",
        "imageUrl": "/textures/items/shaddySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/shaddy/shaddy.gltf"
  },
  {
    "entity": "EntityShadowStalker",
    "displayName": "ShadowStalker",
    "health": 25,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 15,
    "damageMax": 15,
    "spawnTools": [
      {
        "itemId": "Weaponizer.ShadowlordStaff",
        "item": "ShadowlordStaff",
        "usage": "Use ShadowlordStaff to summon EntityShadowStalker.",
        "imageUrl": "/textures/items/shadowlordStaff.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/shadow-stalker/shadow-stalker.gltf"
  },
  {
    "entity": "EntitySpikeback",
    "displayName": "Spikeback",
    "health": 60,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 23,
    "damageMax": 23,
    "spawnTools": [
      {
        "itemId": "Itemizer.SpikebackSlab",
        "item": "SpikebackSlab",
        "usage": "Use SpikebackSlab to summon EntitySpikeback.",
        "imageUrl": "/textures/items/spikebackSlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/spikeback/spikeback.gltf"
  },
  {
    "entity": "EntitySpraggy",
    "displayName": "Spraggy",
    "health": 130,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.SpraggySlab",
        "item": "SpraggySlab",
        "usage": "Use SpraggySlab to summon EntitySpraggy.",
        "imageUrl": "/textures/items/spraggySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/spraggy/spraggy.gltf"
  },
  {
    "entity": "EntityWaggy",
    "displayName": "Waggy",
    "health": 110,
    "healthMin": null,
    "healthMax": null,
    "damageMin": 10,
    "damageMax": 10,
    "spawnTools": [
      {
        "itemId": "Itemizer.WaggySlab",
        "item": "WaggySlab",
        "usage": "Use WaggySlab to summon EntityWaggy.",
        "imageUrl": "/textures/items/waggySlab.png",
        "source": "item/spawn-minion"
      }
    ],
    "model": "/models/_auto-minions/common/waggy/waggy.gltf"
  }
];
